services:
  static-engine-frontend:
    container_name: static-frontend
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://app.staticengine.com}
        NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL:-wss://app.staticengine.com}
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
    restart: always
    env_file:
      - .env
    ports:
      - "4010:5010"
    environment:
      NODE_ENV: production
      PORT: 5010
      HOSTNAME: "0.0.0.0"
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
